Traceback (most recent call last):
  File "/work/morgunov/core/calculations/run_mom.py", line 474, in <module>
    megalodon.run() 
  File "/work/morgunov/core/calculations/run_mom.py", line 391, in run
    self._do_ump2()
  File "/work/morgunov/core/calculations/run_mom.py", line 311, in _do_ump2
    self.umf_core.do_mp2(frozen=self.freeze_orbs)
  File "/home/morgunov/vv/dmp2/sgscf/uhf.py", line 355, in do_mp2
    assert(mf.converged)
AssertionError
